### ISSUE TITLE
Idyll: how does it work?

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#121]
Since I've mostly worked on the tooling side of things, the inner workings of `InteractiveDocument` are still a bit of a mystery to me. Hopefully @mathisonian can drop some knowledge here to help me with my refactorings, but I think a good overview would also be good to have in the docs/site.

Specifically, I'm not clear on the following bits that are specific to Idyll, and not native React concepts.

- [`getChildren()`](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L41)
- [`handleUpdateProps(nodeID)`](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L46)
- [`setStateAndDerived(newState)`](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L65), which is called by code [generated in the node walker](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/visitors/node.js#L105).

I think I'm missing the key insight of exactly _how_ the reactive changes are triggered and propagated through the document.

**Comment by bclinkinbeard** [comment]
Thinking about this a bit more I'm wondering if context might be the perfect way to implement the reactivity and component opt-in features. https://facebook.github.io/react/docs/context.html

We could essentially have `InteractiveDocument` (which should be renamed `IdyllDocument`) provide an event bus that components could subscribe to and dispatch through.

Thoughts?

**Comment by mathisonian** [comment]
This is just in response to the original post, not commenting on `context` yet - 

* `getChildren()` - this turns the AST into react components. The reason it is structured with `walkNode(this, props.componentClasses)` happening outside of the [function definition](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L40) is to do some of the processing work up front in the constructor, and do the minimal amount of work in subsequent re-renders. The expressions need to get re-evaluated each time to be reactive. There are still some optimizations to be done here to further reduce the amount of work that is done after the first render.

* `handleUpdateProps(nodeID)` - This is a function generator for the injected `updateProps` method on the components. Idyll allows custom components a mechanism to change the value of their properties (in turn propegating that update to Idyll's global state). Currently components can only modify their properties bound to a variable. Take this example:

```
[var name:"x" value:1234 ]
[MyCustomComponent prop1:x prop2:1234 ]
```

In this case the custom component may choose to call `this.updateProps({prop1: 4321, prop2: 4321})` to try to change the values of its two props. Because `prop1` is bound to the variable `x`, that variable will be updated to `4321`, but because `prop2` isn't bound to a variable that update call is essentially a noop and on the component's `prop2` will still be 4321.

The reason that we have a generator function to do this instead of just passing one `updateProps` method to everything is because these `property <-> variable` maps may be different for each component. The discussion in https://github.com/idyll-lang/idyll/issues/117 is making me wonder if there is some other semantic (`updateVar`?) that could be exposed in callback functions to update variables directly rather than a property. IMO it makes sense that custom component code can't modify anything other than the props with which it is provided, but in a user defined callback, that seems useful.


* `setStateAndDerived(newState)` - Idyll stores its variables in the state object of the `IdyllDocument` component. This is the mechanism through which we update it. We use it instead of setState to allow for the derived variables to always be in sync with the latest variables. This first updates the values of all the derived variables according to the newState object, and then sets the actual value of the state. The derived variables aren't actually stored on the state object

**Comment by bclinkinbeard** [comment]
Thanks. I can't say I've got my head fully around it all but that does help.

I keep waffling on whether or not the `context` discussion belongs here, but I think it does because the way data is propagated will affect the way components are authored, which will affect the way we parse and construct them.

Basically what I'm wondering is if `IdyllDocument` could provide an `updateIdyll(newState)` function via`context` that would update the derived and regular vars. Once those recalcs are done I think there are two possible routes to take.

- call `setState` to trigger the whole document to re-render the way (I think) it works today.
- notify registered listeners that the Idyll state has changed and allow them to decide whether or not they need to re-render

In the second scenario `IdyllDocument` would also provide an `onIdyllUpdate` function via `context` that components could use to register their interest in updates. We could even provide a `type` param or something that tells listeners what happened. (`stateChange`, `scroll`, `resize`, etc.)

Lastly, if we're concerned that opting in to `context` is too cumbersome, we could update `IdyllComponent` to provide the same API via inheritance, leaving the choice of how to enable integration up to component authors.

**Comment by bclinkinbeard** [comment]
So it finally dawned on me that the AST pretty closely resembles the signature of `React.createElement`. A quick search turned up https://github.com/TechniqueSoftware/react-json-schema, which will convert a JSON schema directly to a React component. The schema it expects doesn't match ours but the code would be pretty easy to adapt, unless making `idyll-compiler` generate their JSON format would be easier.

This seems like it could be a great approach for us as we could simply write a `var` component, a `derived` component, etc. We could optionally do some preprocessing of the JSON to add in reactive hooks and things like that if need be.

Thoughts?

**Comment by mathisonian** [comment]
Could you expand a little more on what you imagine a component API could look like in the second scenario above?

Yeah, the AST resembling what `React.createElement` expects was very intentional. I'm not sure I totally follow what using something like `react-json-schema` gets us other than allowing us to remove that logic from our code base (not that that isn't a nice thing - just making sure I understand). The major difference from our AST and react components is that we have these kind of "typed" properties, e.g. value, variable, expression, and those need to get processed before instantiating the React components. For certain types (expressions in particular), the properties need to be re-evaluated at each render in order to make things work. I guess there's probably a way to do that with context somehow. 

I'd like to avoid forcing people to subscribe to updates on properties that react otherwise would have provided to them in the standard way.

**Comment by mathisonian** [comment]
It seems like using context would inevitably entail moving towards some sort of `redux` style state management. I'm not necessarily opposed to this, but that would be a pretty major update that I'd like to make sure we think all the way through.

**Comment by bclinkinbeard** [comment]
On my phone but will expand on things later this evening.

Can you explain what you mean about Redux and this?

> I'd like to avoid forcing people to subscribe to updates on properties that react otherwise would have provided to them in the standard way.

**Comment by mathisonian** [comment]
From my understanding, in order to know which variables to pass in via context we'd either have to (1) have the users subscribe to updates from specific variables or (2) do some more sophisticated parsing to inject this logic automatically. Right now components can just be written in the standard react way, and not have any additional logic to listen to certain updates. 

I think the discussion will be more clear once you expand on what you are thinking for the API, I might be missing something

**Comment by bclinkinbeard** [comment]
OK, gotcha, now I know what you mean. The advantage of using `react-json-schema` is mainly to avoid writing that code ourself, though adapting it to our own needs is probably more reasonable.

In terms of a component API, something like this could work for components built specifically for Idyll.
```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types'

class SomeComp extends Component {
  componentDidMount() {
    this.context.onIdyllUpdate((o) => {
      console.log('SomeComp received:', o);
    })
  }

  render() {
    const { updateIdyll } = this.context;

    return (
      <div>
        <h2>Some Thing</h2>
        <button onClick={() => updateIdyll({mathew: 'SEA', ben: 'CVG'})}>Dispatch</button>
      </div>
    );
  }
}

SomeComp.contextTypes = {
  onIdyllUpdate: PropTypes.func,
  updateIdyll: PropTypes.func
}

export default SomeComp;
```

Of course the listener could/would be in a separate component from the one doing the dispatching.

I agree we want to enable plain React components to be updated without the author having to opt in. I think we could accomplish this by wrapping components during the construction phase, similar to how it's done now.

Since we already parse the vars and expressions first, we know the full list of "special" props before constructing the component tree. I _think_ it should be fairly simple to tap into the JSON traversal and detect which components have special props being passed in. For the ones that do, we could insert `IdyllComponent` as a wrapper. When the wrapper sees an update to one of the special props, it calls `setState` on itself, triggering an update of the wrapped component.

Does that make sense? This is all still solidifying in my mind as I write this, so hopefully I'm not overlooking some fatal flaw.

**Comment by mathisonian** [comment]
One important thing is to understand the distinction between changing an idyll variable directly, or changing the value of a variable bound to a property. The reason that a component like `Range` can be used effectively in any document with any variable names, is that it only knows about its own properties, and nothing about the variables in the containing document. 

The semantics of the name `updateIdyll` feel more to me like you are trying to update an Idyll variable directly, which could be useful, but is a separate feature from `updateProps`. For example, it could be useful in cases like the processing component where you want to write a callback inline in the document and wouldn't cause a loss of modularity there.

**Comment by mathisonian** [comment]
In this case then would custom components all use an internal state to track the values of things in the `onIdyllUpdate` callback?

**Comment by bclinkinbeard** [comment]
OK, that makes sense. You're right that `updateProps` is actually what we need. Maybe it's how it already works, but do we just need to track the mapping of component props to Idyll state? 

For example, when a component like `Range` calls `updateProps({ value: 3 })` we need to know that actually maps to the Idyll var `fooBar` so we can trigger re-renders of any components that use `fooBar`, right? Which could be done by calling `setState` on the wrapper we inject during creation?

Maybe we don't even need `onIdyllUpdate`. Or maybe it's there but only for monitoring arbitrary state changes?  Maybe we also have `onIdyllScroll`, `onIdyllResize`, etc.

For a bit of additional context I've been picturing the ability to sort of decorate regular components with Idyll primitives by wrapping them.
```
[ScrollAware onEnterView:"sidebar = slide1.jpg"]
  [FullScreen]
    [MiscellaneousBespokeComponent /]
  [/FullScreen]
[/ScrollAware]

[ScrollAware onEnterView:"sidebar = slide2.jpg"]
  [FullScreen]
    [CuteLittleComponent /]
  [/FullScreen]
[/ScrollAware]
```

**Comment by mathisonian** [comment]
> Maybe it's how it already works, but do we just need to track the mapping of component props to Idyll state?

Exactly, the `IdyllDocument` does this by keeping a `bindings` map https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/index.js#L49-L58, and seems like we could make that work with what your're proposing.

It would be really nice if we didn't need `onIdyllUpdate`, or it was just a kind of auxiliary feature. I'm 👍 for `onResize` type of events. The decorator setup is cool!

**Comment by bclinkinbeard** [comment]
Cool, I will take another crack at things on Thursday.

**Comment by bclinkinbeard** [comment]
OK, I have a bunch of scribbled notes and POC code, and I think I see a path forward. Before I go too far I figure we should make sure we're on the same page.

This is roughly how I see the process of turning an AST into an `IdyllDocument` going.

1. `IdyllDocument` would receive `ast`, `componentClasses`, and `datasets` props like it does now
2. The AST would be split into its constituent pieces: vars, data, derived, and elements
3. Everything but the elements would be constructed/evaluated into plain objects like in #120 
4. The elements tree would be walked and pre-processed (while still just an array of plain objects) and any nodes that reference a var (plain or derived) would be wrapped with something we define that monitors the Idyll state, knows which props affect its child, etc.
5. The (now modified) elements tree would be converted into a React element using something like `react-json-schema`
6. PROFIT!

Open questions:
- How much does the structure of `IdyllDocument` need to change? I think we can greatly simplify if not remove `handleUpdateProps` but I'm not sure much else in the class itself needs to change.
- Should we rely on `react-json-schema` or roll our own? I've got POC code that converts our AST to the format they expect, but they'd also have to accept [this PR](https://github.com/TechniqueSoftware/react-json-schema/pull/16). 
- Should ~we~ you update the compiler so it generates an AST closer to what `react-json-schema` does/would? I have no clue how much effort that would be.

I'll move forward in some fashion tomorrow so any feedback you have would be great. :)

**Comment by bclinkinbeard** [comment]
I need to clean up some code and then get the updates propagating, but some nice progress today! I've essentially implemented the process outlined above, except all the wrapper does so far is turn the text pink and log to the console when `updateProps` is called. But it is smart enough to detect which components have props that reference vars and dynamically wrap them!

![kapture 2017-08-18 at 23 00 40](https://user-images.githubusercontent.com/140343/29482947-26a70204-8469-11e7-818b-3d32657b7034.gif)

**Comment by bclinkinbeard** [comment]
@mathisonian I'm stumped. I can't figure out how to get this chart from the editor to work, because the function we construct and evaluate just returns another function. How/where does that function get executed?

```
[Chart
  equation:`(t) => Math.sin(t * frequency)`
  domain:`[0, 2 * Math.PI]`
  samplePoints:1000 /]
```

**Comment by mathisonian** [comment]
That function gets evaluated by the chart component itself (https://github.com/idyll-lang/idyll/blob/master/packages/idyll-components/components/chart.js#L26), but it seems like we'd need to understand which Idyll variables that it accesses in order to make it work with the proposed new setup. 

One option is to use something like https://github.com/ForbesLindesay/acorn-globals to parse the properties and explicitly track which vars are referenced, which would then be handled in the same way as we handle other updating vars. This is something that I've been wanting to add for a while anyways, so it may be a good time to do it. We could even explicitly add these dependencies to the AST if that would make tracking them easier.

**Comment by mathisonian** [comment]
I'm still a little unsure about adding the `react-json-schema` dependency, it seems to be adding a layer of indirection and removing control in exchange for providing logic that isn't that much of a burden to maintain ourselves. Since this is just an internal interface it seems like a lot of the normal benefits of using a schema don't really apply here.

**Comment by bclinkinbeard** [comment]
The problem ended up being that I wasn't tracking all of the expressions we need to. In that particular case it was actually the `domain` attribute that wasn't getting evaluated which was short-circuiting the evaluation of `equation`.

I ended up creating special `__vars__` and `__expr__` props to track everything that has to be evaluated on each render. https://github.com/idyll-lang/idyll/pull/120/commits/b809b2f0a125e4ec8e12bbc21590a958eed20aa2#diff-8efe3bf83f0323daede40949a6fc4ae3 Whenever the Idyll state updates, each wrapper basically just reruns the eval of its own vars and expressions and calls `setState`, trigger a re-render of the wrapped component. https://github.com/idyll-lang/idyll/pull/120/commits/b809b2f0a125e4ec8e12bbc21590a958eed20aa2#diff-8014682ba4a56e519b47060bb3a60e64R44

**Comment by mathisonian** [comment]
Ah okay - so in this case we are still re-evaluating all the expressions on every render?

**Comment by bclinkinbeard** [comment]
I ended up just pulling in the `react-json-schema` code instead of using it as a dependency, because I needed to tweak it slightly. https://github.com/idyll-lang/idyll/pull/120/files#diff-2e04cffd16b792218d75e44ec39e8504

I do think it's a cleaner approach than what we had, with (I think) some extra capabilities around custom props. That makes it easy to decorate things at the AST/JSON stage (like I'm doing heavily in `idyll-document`) and then let the schema translator turn that into a React element.

**Comment by bclinkinbeard** [comment]
Yea, at the moment everything gets re-evaluated every time. I had a state comparison in there for a bit but there was some weirdness. I'm also kind of confused about why `PureComponent`'s `shouldComponentUpdate` doesn't seem to be working.

It should be fairly easy to make https://github.com/idyll-lang/idyll/pull/120/files#diff-8014682ba4a56e519b47060bb3a60e64R160 smarter so that we only call the wrappers/listeners that care about something that actually changed.
