### ISSUE TITLE
make server side rendering optional

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#14]
SSR seems to create some weird loading flash behavior with certain components. Sometimes this seems worse than not rendering on the server at all. 

This would be better as an option rather than always on

**Comment by rreusser** [comment]
I was testing with js disabled to make sure things were in a correct state for SSR, and it seems like more than necessary is not rendering on the server. In particular, [the lorenz page](https://mathisonian.github.io/lorenz/) looks like this:

<img width="655" alt="screen shot 2017-04-17 at 08 29 42" src="https://cloud.githubusercontent.com/assets/572717/25088901/231a5406-2348-11e7-9538-4f7a80fb93d6.png">

Was going to debug that since it seems like perhaps just an initialization that's preventing static things like links or headings from rendering.
