### ISSUE TITLE
Trouble displaying data from `refs`

### ISSUE THREAD

**Issue by tonyhschu** [idyll-lang/idyll#151]
Code:
```
[Display value:`refs.test.scrollProgress.y` /]
[section ref:"test"]
Scroll

Scroll

Scroll

Scroll
[/section]
```

Expected behavior: The Display component should show the scroll progress value.

Actual behavior: Nothing shows up.

Twitter discussion - https://twitter.com/mathisonian/status/906991304134991873

Matt's suggestion: add the -r flag e.g. `idyll -r index.idl` which does work.

**Comment by mathisonian** [comment]
The problem seems to be that when the refs get passed through the SSR pipeline they transform the AST and don't reset it for the client (see here https://github.com/idyll-lang/idyll-interactive-document/blob/master/src/visitors/vars.js#L115) - this leads to a state where the refs are correctly set on the server, but not in the client where we actually need them. 

I believe @bclinkinbeard's re-architecting work fixes this, so we can close this once the next release goes out
