### ISSUE TITLE
Can't build standalone JS bundle

### ISSUE THREAD

**Issue by ejb** [idyll-lang/idyll#23]
The documentation states that this combination of flags should build a bundle:

    idyll my-file.idl --build > bundle.js

But when I run this on my project...

    ./node_modules/idyll/bin/idyll.js index.idl --build > bundle.js

... I just get the stdout echoed to the file.

```


Spellcheck:
No misspellings found.
```

Is the documentation out of date, or am I doing something wrong?

**Comment by rreusser** [comment]
#18 suggests it might be a documentation issue, but I'm not 100% certain. For a start, can you try the commands the generator adds? See: https://github.com/idyll-lang/generator-idyll/blob/master/generators/app/templates/_package.json#L5-L6

**Comment by mathisonian** [comment]
This is my fault - the README is out of sync with the website since we update the build process.

It no longer pipes anything to standard out - 

```
idyll my-file.idl --output ./path/to/output --build
```

If you don't provide `--output` it will default to `./build`

**Comment by ejb** [comment]
Why was the standalone JS bundle option removed? Just curious, it would have been useful for my own use case – I'd like to integrate it into an existing PHP template.

**Comment by rreusser** [comment]
My fault. 😬 The reasoning was that it was a bit confusing/surprising that it output the build result to stdout *but also* wrote a number of other files at the same time. I hope that wasn't misguided input. 😞

**Comment by mathisonian** [comment]
There's some detailed discussion of it here - https://github.com/idyll-lang/idyll/issues/16 

Short version is that it the old build setup was weird because it was piping JS to stdout, but also was generating other files directly, so we wanted to unify how this works. You should still be able to drop in the generated `.js` file and use it with your PHP template. 

I think we're still figuring out how to make this as flexible as possible for integrating with different build systems, so if you have suggestions I'm definitely open to hearing them

**Comment by mathisonian** [comment]
@ejb the API now supports this use case:

```
var idyll = require('idyll');

idyll('index.idl', options, function(output) {
    console.log(output.js);
})
```
