### ISSUE TITLE
Grant Funded Work Planning 

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#243]
This supersedes #202 but I've not ported that info over yet. Just capturing existing chats for the moment.

## Things we understand enough to start building
> API parity, components from multiple directories, any other pieces to support blogging

## Things that need more discussion
> one thing i want to do is solidify a model of page layout model so that we can be more structured in our "responsive layouts"
> which might involve just adding a CSS build system and exposing variables like "paragraph width", "margin size" etc

**Comment by mathisonian** [comment]
For the CSS I think there are three things that we want to accomplish:

1. (To support API parity) update `<IdyllDocument />` so that it can accept a `theme` prop and inject styles scoped to its output.
2. Add support for variables in the CSS. The "how" of this one is up in the air, it could include switching to a css-in-js style solution (which might also be useful for 1), or adding a preprocessing step like Sass.
3. Refactor how responsive layouts are done given the updated style infrastructure.

Hopefully 1 and 2 are well defined enough for the short term. I think 3 will need a bit more thought and discussion.

**Comment by bclinkinbeard** [comment]
I just remembered something we talked about but I have no idea when or where. I guess it's kinda sorta part of the API parity work, but it's the topic of module formats. I guess right now we're supporting CommonJS in the Node API/CLI, and ES in the browser/IdyllDocument.

**Comment by mathisonian** [comment]
> I just remembered something we talked about but I have no idea when or where. I guess it's kinda sorta part of the API parity work, but it's the topic of module formats. I guess right now we're supporting CommonJS in the Node API/CLI, and ES in the browser/IdyllDocument.

I'm happy to converge on whatever module format internally, so long as it is easy for people to use/install. I guess the main issue is how we expect the components to be formatted?

Currently we expect components to be precompiled, though if we want to support editing of component code dynamically (i.e. in a running `IdyllDocument`) we'd need to have access to the raw source for this. I'm not sure how allowing arbitrary components from npm factors in to this - who knows how those will be bundled.
