### ISSUE TITLE
propagate errors from compiler into the browser

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#31]
a great feature of budo is that it shows errors directly in the browser so you know when something isn't compiling and it doesn't get lost in the terminal. idyll should do this too.

**Comment by mathisonian** [comment]
I've added initial support for this in https://github.com/idyll-lang/idyll/tree/error-messages but have a lot of clean up to do!

**Comment by joshuahhh** [comment]
Why is this issue closed? I don't think it was implemented – I still get errors in the console, rather than in the browser.

FWIW, this is my #1 workflow problem with Idyll. I am going back and forth between my editor and the browser, and then suddenly the browser stops updating, and I think it's because something is broken, but it turns out it's because there's some syntax error hiding in the console. It's quite frustrating!

(Thanks!)

**Comment by mathisonian** [comment]
Thanks for pointing this out @joshuahhh - I can confirm this is still an issue. 

I'm working on a patch.

**Comment by joshuahhh** [comment]
That's great – thanks so much!

Not sure what you were planning, but my favorite-to-least-favorite ordering for interfaces is:
1. an impossible-to-miss but otherwise unobtrusive overlay on the document,
2. replacing the document with an error message,
3. (way worse) a message in the console.

Maybe unrelated: I've found that some errors (syntax errors in custom-component Javascript, maybe?) straight-up exit Idyll. Should I make a new issue for that?

**Comment by mathisonian** [comment]
Yes, could you make a separate issue for those?

**Comment by mathisonian** [comment]
Closed by #458
