### ISSUE TITLE
basePath option has some weird behavior

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#417]
If I run the command:

```
idyll -i my-posts/post.idyll -o build/
```

then the `basePath` will be set as `my-posts/` and the build output will go to `my-posts/build/` this is pretty strange.

**Comment by hmuar** [comment]
How should the `build/` path be resolved? Should the `build` directory be relative to where the command was run? So if input path is
```
/Users/testUser/idyll-projects/my-posts/post.idyll
```
And your current directory is
```
/Users/testUser/idyll-projects
```
And you run command
```
idyll -i my-posts/post.idyll -o build/
```
Should the final build directory be:
```
/Users/testUser/idyll-projects/build/
```
If this is the case, then as part of this fix, would it be ok for me to modify `idyll/packages/idyll-cli/test/batteries-included/test.js` so that the idyll instance is passed in an output argument too?
```javascript
const PROJECT_BUILD_DIR = join(PROJECT_DIR, 'build');
idyll({
  inputFile: join(PROJECT_DIR, 'index.idl'),
  output: PROJECT_BUILD_DIR, // <<------- can i add this line ?
  compiler: {
    spellcheck: false
  },
  minify: false
}).on('update', (o) => {
```
Otherwise, the proper behavior after doing this fix puts the output `build/` directory in whatever current directory the test is run from and makes the tests fail because it is expecting
```
idyll/packages/idyll-cli/test/batteries-included/build
```
but for me the build dir instead ends up being
```
idyll/packages/idyll-cli/build
```

**Comment by mathisonian** [comment]
@hmuar I think that the behavior you are describing (build directory be relative to where the command was run) is the most intuitive. I think adding that option to the test totally makes sense.

At some point we'll want to support a workflow that makes it easy to get `my-posts/post-1.idyll` to build into `build/post-1/`, `my-posts/post-2.idyll`, `build/post-2/`, etc, without writing all those paths manually, but I think that is a separate issue.
