### ISSUE TITLE
How to write multi articles in one idyll project.

### ISSUE THREAD

**Issue by geekplux** [idyll-lang/idyll#421]
Thanks for this great project. I used to be a visualization student, so I think idyll will be perfect solution for writing interactive article.

I have tried to use it to create a post in command line, but I found it can only contain one article in one idyll project. So how to place or organize multi posts in one project? This maybe useful for blog or book users.

**Comment by mathisonian** [comment]
Hey @geekplux,

We are still working on incorporating multipage articles into Idyll core (right now it is designed so that one idyll project === one post), however there are a few options.

* [Idyll flask](https://github.com/cmakler/idyll-flask) is a flask based multipage solution that you can use today to create a multi-page idyll site. 
* [Idyll book](https://github.com/mathisonian/idyll-book) is a work-in-progress that will probably be closer to the core solution, it doesn't quite work with the stable version of Idyll yet however. 
* You might also write a custom script to handle the compilitation of multiple different pages. See "Using Idyll as an API" at bottom of [this page](https://idyll-lang.org/docs/configuration-and-styles).

**Comment by geekplux** [comment]
Cool 👍 Idyll book maybe fit more, looking forward to this breaking change. I'd also try to write some scripts to implement a demo.

**Comment by geekplux** [comment]
great thanks, I'll have a try

**Comment by mathisonian** [comment]
We've made a bit of progress here, and things with the CLI are very close to enabling this setup without requiring any external tool or lib. Once #510 is addressed I'll do a write-up on how to best setup a multipage project with the latest Idyll.

**Comment by mathisonian** [comment]
Here's a working example that doesn't require any additional scripts/logic to build: https://github.com/idyll-lang/idyll-multipage-example

**Comment by mathisonian** [comment]
The `idyll create` command can now be used to create a multipage (blog, book, etc) project. To do this simply select "multipage" as the template when running the command. I'm closing this issue sense there's a canonical way of doing this now.
