### ISSUE TITLE
Idyll Tables Not Rendering in React

### ISSUE THREAD

**Issue by witang** [idyll-lang/idyll#431]
Hi @mathisonian 

I'm trying to create a basic table in Idyll markup using the [Table /] component, and then embed this within my React application. This the table I'm trying to render:
```
[Table data: `[{x: 'A', y: 22}, {x: 'B', y: 34}]` /]
```
When I paste this into some basic Idyll markup and host it as an individual page, the table renders perfectly. However, when I try to copy the same table markup into the IdyllDocument component as follows...

```
import * as idyll_components from 'idyll-components';
```
```
<div className="SampleComponent">
    <IdyllDocument
        markup = { "[Table data:`[{x: 'A', y: 22}, {x: 'B', y: 34}]` /]" }
        components = { idyll_components }
    />
</div>
```
...it ends up rendering this: 

![screen shot 2018-11-07 at 10 42 03 am](https://user-images.githubusercontent.com/35241613/48152885-deb31a80-e279-11e8-8529-30a962de8ff5.png)

I assumed that Table was a built in component that shipped with Idyll, but is there perhaps an additional CSS or React import that I'm missing? 

Thanks.

**Comment by mathisonian** [comment]
Hey @witang,

Yeah, it seems like there's CSS for this component that is available in Idyll's themes, but doesn't get injected into the page if you are using the `IdyllDocument` component standalone. 

To get the styles, you can get it from the `idyll-themes` package and inject it yourself:

```
import { github } from 'idyll-themes';

// github.styles is a string of CSS styles you can inject into the page
```

We may add an `injectCSS` option to the document component so that the component takes care of this for you.

**Comment by witang** [comment]
Thanks for the response. So I was able to get the table to render as expected, but I'm having some difficulty overriding some of the CSS (for both tables and Idyll in general) that comes by default. 

For example, I noticed within the module source code that in both the blog and centered layouts that the max-width of idyll-text-containers come as a hard 600px and that this is set as an inline style property, giving it top priority. Ideally, I'd like to expand the the table to fill its parent container instead, but short of writing my own new layout, I'm not quite sure how to proceed overriding this and other properties using my own stylesheets. I apologize in advance if I'm missing something obvious. 

Thanks.

**Comment by mathisonian** [comment]
Thanks @witang, sorry for the delay. That seems like a totally valid concern, and I think we should do better about separating out the component specific CSS from the layout/theme CSS so that it is easy to work on one without the other. 

You should always be able to add your own CSS rules to override e.g. the max-width that idyll sets, but in this case I think it might be easier to just grab the table CSS directly and use that. You can that our table dependency uses here: https://unpkg.com/react-table@6.8.6/react-table.css.

**Comment by mathisonian** [comment]
The latest version of the text containers set all styles via CSS, so modifying layout properties should be more straightforward now. I'm going to close since there's not a specific issue, but feel free to open if there are still problems.
