### ISSUE TITLE
Passing a text prop to a component unexpectedly adds the prop value as a child

### ISSUE THREAD

**Issue by kmdupr33** [idyll-lang/idyll#503]
**To Reproduce**

See [this saved idyll editor](https://idyll-lang.org/editor/6b6c467c-7747-48b7-b7dc-020d4a06cea2), which simply has `[div text:"Hello" /]` in the editor side and shows "hello" as output.

**Expected behavior**
I don't expect the value of a text prop to show up as a child of the component.

**Screenshots**
![image](https://user-images.githubusercontent.com/5463526/58430013-bb18bb80-8075-11e9-8785-9637f62c615e.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by mathisonian** [comment]
Weird! 

I'm not sure if this is a React behavior or an idyll introduced error. Going to look into this more and report back.

**Comment by kmdupr33** [comment]
Yeah I had the same thought. I checked that, however. It doesn't appear to be a feature of react.

**Comment by mathisonian** [comment]
Thanks for checking that out. This seems to be related to how we're representing components via a JSON schema. You can see the bug here https://github.com/idyll-lang/idyll/blob/master/packages/idyll-document/src/utils/schema2element.js#L43-L46. I believe that check could be safely removed as we don't set the text property anywhere when generating the schema from the AST.
