### ISSUE TITLE
Issues with Node v15

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#694]
**Describe the bug**
It appears that there may be some incompatibilities with node v15. See https://github.com/idyll-lang/idyll/issues/680 and https://github.com/idyll-lang/idyll/issues/693. 

I'll keep this issue open to track until we've confirmed a fix. For now the recommended solution is to use [https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm) to install another version (e.g. v14) and use idyll with that version.

**Comment by rogerfitz** [comment]
I took a stab at this last night but how do I go about testing `npm install idyll` would work with the branch I'm working on? I got it passing tests with node 15 by upgrading the react-tooltip library. Related issue here https://github.com/npm/cli/issues/1734, `npm install --legacy-peer-deps ..` should work too but the dependency issue was patched in react-tooltip 4.0.1. Creating PR showing what I did here https://github.com/idyll-lang/idyll/pull/706

**Comment by mathisonian** [comment]
If you can run `lerna clean && lerna bootstrap` in the root of the project with node15 then it should be okay on the dependency side. However I noticed that there is also an issue creating new projects: running `idyll create` always says that installing dependencies failed, even when it didn't. 

A little setup required to test the global command line commands with the local dev version of idyll:

- make a new folder
- run `npm init` to create a package json
- inside the new package.json add `scripts:  { "create-idyll-project": "idyll create" }` 
- inside that folder run `yarn link idyll` so that the local copy of idyll is available
- run `yarn run create-idyll-project` to run the idyll create command with the dev version

**Comment by rogerfitz** [comment]
FYI #707 is main PR now

Thanks for these instructions. I was able to get it running but found an issue with yargs and the commandlineArgs library I introduced in idyll-cli. It was saying command "create" not found https://github.com/idyll-lang/idyll/pull/707/commits/386e9cf5d34fed2ce715249d5f0a6fdbf0c8c5a4. Interestingly when I installed idyll 5.3.4 `idyll create` was fine but maybe this is just a yarn link thing?

I added a commit fixing that onto #707 since it was pretty small but would you rather I isolate out the commit to something linked to the issue and another branch/PR? Wasn't sure how detailed you like to be about those sorts of things

**Comment by mathisonian** [comment]
Thanks @rogerfitz! I merged in #707 to get that `idyll create` fix in. In general the smaller / more tightly scoped a PR is the quicker I'll be able to review and merge but I am flexible and happy to have fixes submitted in any form.

**Comment by mathisonian** [comment]
I'm reopening because of reports that this hasn't been completely resolved. See #723
